/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ApplicationId = IDL.Text;
export const DocumentType = IDL.Variant({
  'other' : IDL.Text,
  'bankStatement' : IDL.Null,
  'incomeProof' : IDL.Null,
  'identityProof' : IDL.Null,
  'photograph' : IDL.Null,
  'addressProof' : IDL.Null,
});
export const DocumentUploadInput = IDL.Record({
  'applicationId' : IDL.Opt(ApplicationId),
  'docType' : DocumentType,
  'fileReference' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const DocumentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : VerificationStatus,
  'applicationId' : IDL.Opt(ApplicationId),
  'rejectionReason' : IDL.Opt(IDL.Text),
  'customerId' : UserId,
  'docType' : DocumentType,
  'uploadedAt' : Timestamp,
  'fileReference' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : DocumentRecord,
  'err' : IDL.Text,
});
export const AdminApproveInput = IDL.Record({
  'interestRate' : IDL.Float64,
  'adminNotes' : IDL.Opt(IDL.Text),
  'approvedAmount' : IDL.Nat,
});
export const ApplicationStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'kycPending' : IDL.Null,
  'underReview' : IDL.Null,
  'documentsPending' : IDL.Null,
  'disbursed' : IDL.Null,
  'cibilPending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
  'paymentPending' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const StripePayment = IDL.Record({
  'status' : PaymentStatus,
  'createdAt' : Timestamp,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : IDL.Opt(Timestamp),
  'paymentIntentId' : IDL.Text,
});
export const DisbursementRecord = IDL.Record({
  'referenceNumber' : IDL.Text,
  'ifscCode' : IDL.Text,
  'applicationId' : ApplicationId,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Nat,
  'disbursedAt' : Timestamp,
});
export const LoanPurpose = IDL.Variant({
  'other' : IDL.Text,
  'home' : IDL.Null,
  'education' : IDL.Null,
  'personal' : IDL.Null,
  'business' : IDL.Null,
  'vehicle' : IDL.Null,
  'medical' : IDL.Null,
});
export const LoanApplication = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'approvedAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Opt(Timestamp),
  'processingFeePayment' : IDL.Opt(StripePayment),
  'updatedAt' : Timestamp,
  'tenureMonths' : IDL.Nat,
  'interestRate' : IDL.Opt(IDL.Float64),
  'cibilRecordId' : IDL.Opt(IDL.Text),
  'customerId' : UserId,
  'disbursement' : IDL.Opt(DisbursementRecord),
  'adminNotes' : IDL.Opt(IDL.Text),
  'amountRequested' : IDL.Nat,
  'approvedAmount' : IDL.Opt(IDL.Nat),
  'purpose' : LoanPurpose,
});
export const Result_1 = IDL.Variant({
  'ok' : LoanApplication,
  'err' : IDL.Text,
});
export const IdentityType = IDL.Variant({
  'pan' : IDL.Null,
  'aadhaar' : IDL.Null,
  'drivingLicense' : IDL.Null,
});
export const KycRecord = IDL.Record({
  'status' : VerificationStatus,
  'identityType' : IdentityType,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'identityNumber' : IDL.Text,
  'customerId' : UserId,
});
export const CustomerProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CibilRecord = IDL.Record({
  'requestId' : IDL.Text,
  'isEligible' : IDL.Bool,
  'score' : IDL.Nat,
  'checkedAt' : Timestamp,
  'customerId' : UserId,
  'reportSummary' : IDL.Text,
});
export const ApplicationDetails = IDL.Record({
  'kyc' : IDL.Opt(KycRecord),
  'documents' : IDL.Vec(DocumentRecord),
  'application' : LoanApplication,
  'customer' : IDL.Opt(CustomerProfile),
  'cibil' : IDL.Opt(CibilRecord),
});
export const ApplicationFilter = IDL.Variant({
  'all' : IDL.Null,
  'byCustomer' : UserId,
  'byStatus' : ApplicationStatus,
});
export const ApplicationSummary = IDL.Record({
  'id' : ApplicationId,
  'customerName' : IDL.Text,
  'status' : ApplicationStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'customerId' : UserId,
  'amountRequested' : IDL.Nat,
});
export const DisbursementInput = IDL.Record({
  'referenceNumber' : IDL.Text,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const AdminRejectInput = IDL.Record({ 'rejectionReason' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : KycRecord, 'err' : IDL.Text });
export const CustomerProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : CustomerProfile, 'err' : IDL.Text });
export const LoanApplicationInput = IDL.Record({
  'tenureMonths' : IDL.Nat,
  'amountRequested' : IDL.Nat,
  'purpose' : LoanPurpose,
});
export const Result_3 = IDL.Variant({ 'ok' : CibilRecord, 'err' : IDL.Text });
export const KycSubmitInput = IDL.Record({
  'identityType' : IdentityType,
  'identityNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([UserId], [Result_5], []),
  'addDocument' : IDL.Func([DocumentUploadInput], [Result_4], []),
  'adminApproveApplication' : IDL.Func(
      [ApplicationId, AdminApproveInput],
      [Result_1],
      [],
    ),
  'adminGetApplicationDetails' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(ApplicationDetails)],
      ['query'],
    ),
  'adminListApplications' : IDL.Func(
      [ApplicationFilter],
      [IDL.Vec(ApplicationSummary)],
      ['query'],
    ),
  'adminRecordDisbursement' : IDL.Func(
      [ApplicationId, DisbursementInput],
      [Result_1],
      [],
    ),
  'adminRejectApplication' : IDL.Func(
      [ApplicationId, AdminRejectInput],
      [Result_1],
      [],
    ),
  'adminReviewDocument' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [Result_4],
      [],
    ),
  'adminReviewKyc' : IDL.Func(
      [UserId, IDL.Bool, IDL.Opt(IDL.Text)],
      [Result_2],
      [],
    ),
  'createCustomerProfile' : IDL.Func([CustomerProfileInput], [Result], []),
  'createLoanApplication' : IDL.Func([LoanApplicationInput], [Result_1], []),
  'getMyApplication' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(LoanApplication)],
      ['query'],
    ),
  'getMyCibilRecord' : IDL.Func([], [IDL.Opt(CibilRecord)], ['query']),
  'getMyDocuments' : IDL.Func(
      [IDL.Opt(ApplicationId)],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'getMyKycStatus' : IDL.Func([], [IDL.Opt(KycRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'listMyApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'recordCibilCheck' : IDL.Func(
      [UserId, IDL.Nat, IDL.Text, IDL.Text],
      [Result_3],
      [],
    ),
  'recordPayment' : IDL.Func([ApplicationId, StripePayment], [Result_1], []),
  'submitKyc' : IDL.Func([KycSubmitInput], [Result_2], []),
  'submitLoanApplication' : IDL.Func([ApplicationId], [Result_1], []),
  'updateCustomerProfile' : IDL.Func([CustomerProfileInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ApplicationId = IDL.Text;
  const DocumentType = IDL.Variant({
    'other' : IDL.Text,
    'bankStatement' : IDL.Null,
    'incomeProof' : IDL.Null,
    'identityProof' : IDL.Null,
    'photograph' : IDL.Null,
    'addressProof' : IDL.Null,
  });
  const DocumentUploadInput = IDL.Record({
    'applicationId' : IDL.Opt(ApplicationId),
    'docType' : DocumentType,
    'fileReference' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const DocumentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : VerificationStatus,
    'applicationId' : IDL.Opt(ApplicationId),
    'rejectionReason' : IDL.Opt(IDL.Text),
    'customerId' : UserId,
    'docType' : DocumentType,
    'uploadedAt' : Timestamp,
    'fileReference' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : DocumentRecord, 'err' : IDL.Text });
  const AdminApproveInput = IDL.Record({
    'interestRate' : IDL.Float64,
    'adminNotes' : IDL.Opt(IDL.Text),
    'approvedAmount' : IDL.Nat,
  });
  const ApplicationStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'kycPending' : IDL.Null,
    'underReview' : IDL.Null,
    'documentsPending' : IDL.Null,
    'disbursed' : IDL.Null,
    'cibilPending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
    'paymentPending' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const StripePayment = IDL.Record({
    'status' : PaymentStatus,
    'createdAt' : Timestamp,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : IDL.Opt(Timestamp),
    'paymentIntentId' : IDL.Text,
  });
  const DisbursementRecord = IDL.Record({
    'referenceNumber' : IDL.Text,
    'ifscCode' : IDL.Text,
    'applicationId' : ApplicationId,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Nat,
    'disbursedAt' : Timestamp,
  });
  const LoanPurpose = IDL.Variant({
    'other' : IDL.Text,
    'home' : IDL.Null,
    'education' : IDL.Null,
    'personal' : IDL.Null,
    'business' : IDL.Null,
    'vehicle' : IDL.Null,
    'medical' : IDL.Null,
  });
  const LoanApplication = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'approvedAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Opt(Timestamp),
    'processingFeePayment' : IDL.Opt(StripePayment),
    'updatedAt' : Timestamp,
    'tenureMonths' : IDL.Nat,
    'interestRate' : IDL.Opt(IDL.Float64),
    'cibilRecordId' : IDL.Opt(IDL.Text),
    'customerId' : UserId,
    'disbursement' : IDL.Opt(DisbursementRecord),
    'adminNotes' : IDL.Opt(IDL.Text),
    'amountRequested' : IDL.Nat,
    'approvedAmount' : IDL.Opt(IDL.Nat),
    'purpose' : LoanPurpose,
  });
  const Result_1 = IDL.Variant({ 'ok' : LoanApplication, 'err' : IDL.Text });
  const IdentityType = IDL.Variant({
    'pan' : IDL.Null,
    'aadhaar' : IDL.Null,
    'drivingLicense' : IDL.Null,
  });
  const KycRecord = IDL.Record({
    'status' : VerificationStatus,
    'identityType' : IdentityType,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'identityNumber' : IDL.Text,
    'customerId' : UserId,
  });
  const CustomerProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CibilRecord = IDL.Record({
    'requestId' : IDL.Text,
    'isEligible' : IDL.Bool,
    'score' : IDL.Nat,
    'checkedAt' : Timestamp,
    'customerId' : UserId,
    'reportSummary' : IDL.Text,
  });
  const ApplicationDetails = IDL.Record({
    'kyc' : IDL.Opt(KycRecord),
    'documents' : IDL.Vec(DocumentRecord),
    'application' : LoanApplication,
    'customer' : IDL.Opt(CustomerProfile),
    'cibil' : IDL.Opt(CibilRecord),
  });
  const ApplicationFilter = IDL.Variant({
    'all' : IDL.Null,
    'byCustomer' : UserId,
    'byStatus' : ApplicationStatus,
  });
  const ApplicationSummary = IDL.Record({
    'id' : ApplicationId,
    'customerName' : IDL.Text,
    'status' : ApplicationStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'customerId' : UserId,
    'amountRequested' : IDL.Nat,
  });
  const DisbursementInput = IDL.Record({
    'referenceNumber' : IDL.Text,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const AdminRejectInput = IDL.Record({ 'rejectionReason' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : KycRecord, 'err' : IDL.Text });
  const CustomerProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : CustomerProfile, 'err' : IDL.Text });
  const LoanApplicationInput = IDL.Record({
    'tenureMonths' : IDL.Nat,
    'amountRequested' : IDL.Nat,
    'purpose' : LoanPurpose,
  });
  const Result_3 = IDL.Variant({ 'ok' : CibilRecord, 'err' : IDL.Text });
  const KycSubmitInput = IDL.Record({
    'identityType' : IdentityType,
    'identityNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([UserId], [Result_5], []),
    'addDocument' : IDL.Func([DocumentUploadInput], [Result_4], []),
    'adminApproveApplication' : IDL.Func(
        [ApplicationId, AdminApproveInput],
        [Result_1],
        [],
      ),
    'adminGetApplicationDetails' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(ApplicationDetails)],
        ['query'],
      ),
    'adminListApplications' : IDL.Func(
        [ApplicationFilter],
        [IDL.Vec(ApplicationSummary)],
        ['query'],
      ),
    'adminRecordDisbursement' : IDL.Func(
        [ApplicationId, DisbursementInput],
        [Result_1],
        [],
      ),
    'adminRejectApplication' : IDL.Func(
        [ApplicationId, AdminRejectInput],
        [Result_1],
        [],
      ),
    'adminReviewDocument' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'adminReviewKyc' : IDL.Func(
        [UserId, IDL.Bool, IDL.Opt(IDL.Text)],
        [Result_2],
        [],
      ),
    'createCustomerProfile' : IDL.Func([CustomerProfileInput], [Result], []),
    'createLoanApplication' : IDL.Func([LoanApplicationInput], [Result_1], []),
    'getMyApplication' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(LoanApplication)],
        ['query'],
      ),
    'getMyCibilRecord' : IDL.Func([], [IDL.Opt(CibilRecord)], ['query']),
    'getMyDocuments' : IDL.Func(
        [IDL.Opt(ApplicationId)],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'getMyKycStatus' : IDL.Func([], [IDL.Opt(KycRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'listMyApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'recordCibilCheck' : IDL.Func(
        [UserId, IDL.Nat, IDL.Text, IDL.Text],
        [Result_3],
        [],
      ),
    'recordPayment' : IDL.Func([ApplicationId, StripePayment], [Result_1], []),
    'submitKyc' : IDL.Func([KycSubmitInput], [Result_2], []),
    'submitLoanApplication' : IDL.Func([ApplicationId], [Result_1], []),
    'updateCustomerProfile' : IDL.Func([CustomerProfileInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };