/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminApproveInput {
  'interestRate' : number,
  'adminNotes' : [] | [string],
  'approvedAmount' : bigint,
}
export interface AdminRejectInput { 'rejectionReason' : string }
export interface ApplicationDetails {
  'kyc' : [] | [KycRecord],
  'documents' : Array<DocumentRecord>,
  'application' : LoanApplication,
  'customer' : [] | [CustomerProfile],
  'cibil' : [] | [CibilRecord],
}
export type ApplicationFilter = { 'all' : null } |
  { 'byCustomer' : UserId } |
  { 'byStatus' : ApplicationStatus };
export type ApplicationId = string;
export type ApplicationStatus = { 'submitted' : null } |
  { 'kycPending' : null } |
  { 'underReview' : null } |
  { 'documentsPending' : null } |
  { 'disbursed' : null } |
  { 'cibilPending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null } |
  { 'paymentPending' : null };
export interface ApplicationSummary {
  'id' : ApplicationId,
  'customerName' : string,
  'status' : ApplicationStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'customerId' : UserId,
  'amountRequested' : bigint,
}
export interface CibilRecord {
  'requestId' : string,
  'isEligible' : boolean,
  'score' : bigint,
  'checkedAt' : Timestamp,
  'customerId' : UserId,
  'reportSummary' : string,
}
export interface CustomerProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'address' : string,
  'phone' : string,
}
export interface CustomerProfileInput {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DisbursementInput {
  'referenceNumber' : string,
  'ifscCode' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export interface DisbursementRecord {
  'referenceNumber' : string,
  'ifscCode' : string,
  'applicationId' : ApplicationId,
  'bankName' : string,
  'accountNumber' : string,
  'amount' : bigint,
  'disbursedAt' : Timestamp,
}
export interface DocumentRecord {
  'id' : string,
  'status' : VerificationStatus,
  'applicationId' : [] | [ApplicationId],
  'rejectionReason' : [] | [string],
  'customerId' : UserId,
  'docType' : DocumentType,
  'uploadedAt' : Timestamp,
  'fileReference' : string,
}
export type DocumentType = { 'other' : string } |
  { 'bankStatement' : null } |
  { 'incomeProof' : null } |
  { 'identityProof' : null } |
  { 'photograph' : null } |
  { 'addressProof' : null };
export interface DocumentUploadInput {
  'applicationId' : [] | [ApplicationId],
  'docType' : DocumentType,
  'fileReference' : string,
}
export type IdentityType = { 'pan' : null } |
  { 'aadhaar' : null } |
  { 'drivingLicense' : null };
export interface KycRecord {
  'status' : VerificationStatus,
  'identityType' : IdentityType,
  'rejectionReason' : [] | [string],
  'submittedAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'identityNumber' : string,
  'customerId' : UserId,
}
export interface KycSubmitInput {
  'identityType' : IdentityType,
  'identityNumber' : string,
}
export interface LoanApplication {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'approvedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'submittedAt' : [] | [Timestamp],
  'processingFeePayment' : [] | [StripePayment],
  'updatedAt' : Timestamp,
  'tenureMonths' : bigint,
  'interestRate' : [] | [number],
  'cibilRecordId' : [] | [string],
  'customerId' : UserId,
  'disbursement' : [] | [DisbursementRecord],
  'adminNotes' : [] | [string],
  'amountRequested' : bigint,
  'approvedAmount' : [] | [bigint],
  'purpose' : LoanPurpose,
}
export interface LoanApplicationInput {
  'tenureMonths' : bigint,
  'amountRequested' : bigint,
  'purpose' : LoanPurpose,
}
export type LoanPurpose = { 'other' : string } |
  { 'home' : null } |
  { 'education' : null } |
  { 'personal' : null } |
  { 'business' : null } |
  { 'vehicle' : null } |
  { 'medical' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export type Result = { 'ok' : CustomerProfile } |
  { 'err' : string };
export type Result_1 = { 'ok' : LoanApplication } |
  { 'err' : string };
export type Result_2 = { 'ok' : KycRecord } |
  { 'err' : string };
export type Result_3 = { 'ok' : CibilRecord } |
  { 'err' : string };
export type Result_4 = { 'ok' : DocumentRecord } |
  { 'err' : string };
export type Result_5 = { 'ok' : string } |
  { 'err' : string };
export interface StripePayment {
  'status' : PaymentStatus,
  'createdAt' : Timestamp,
  'currency' : string,
  'amount' : bigint,
  'paidAt' : [] | [Timestamp],
  'paymentIntentId' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'addAdmin' : ActorMethod<[UserId], Result_5>,
  'addDocument' : ActorMethod<[DocumentUploadInput], Result_4>,
  'adminApproveApplication' : ActorMethod<
    [ApplicationId, AdminApproveInput],
    Result_1
  >,
  'adminGetApplicationDetails' : ActorMethod<
    [ApplicationId],
    [] | [ApplicationDetails]
  >,
  'adminListApplications' : ActorMethod<
    [ApplicationFilter],
    Array<ApplicationSummary>
  >,
  'adminRecordDisbursement' : ActorMethod<
    [ApplicationId, DisbursementInput],
    Result_1
  >,
  'adminRejectApplication' : ActorMethod<
    [ApplicationId, AdminRejectInput],
    Result_1
  >,
  'adminReviewDocument' : ActorMethod<
    [string, boolean, [] | [string]],
    Result_4
  >,
  'adminReviewKyc' : ActorMethod<[UserId, boolean, [] | [string]], Result_2>,
  'createCustomerProfile' : ActorMethod<[CustomerProfileInput], Result>,
  'createLoanApplication' : ActorMethod<[LoanApplicationInput], Result_1>,
  'getMyApplication' : ActorMethod<[ApplicationId], [] | [LoanApplication]>,
  'getMyCibilRecord' : ActorMethod<[], [] | [CibilRecord]>,
  'getMyDocuments' : ActorMethod<[[] | [ApplicationId]], Array<DocumentRecord>>,
  'getMyKycStatus' : ActorMethod<[], [] | [KycRecord]>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'listMyApplications' : ActorMethod<[], Array<LoanApplication>>,
  'recordCibilCheck' : ActorMethod<[UserId, bigint, string, string], Result_3>,
  'recordPayment' : ActorMethod<[ApplicationId, StripePayment], Result_1>,
  'submitKyc' : ActorMethod<[KycSubmitInput], Result_2>,
  'submitLoanApplication' : ActorMethod<[ApplicationId], Result_1>,
  'updateCustomerProfile' : ActorMethod<[CustomerProfileInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];