/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DocumentType = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bankStatement";
    bankStatement: null;
} | {
    __kind__: "incomeProof";
    incomeProof: null;
} | {
    __kind__: "identityProof";
    identityProof: null;
} | {
    __kind__: "photograph";
    photograph: null;
} | {
    __kind__: "addressProof";
    addressProof: null;
};
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: KycRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface DocumentRecord {
    id: string;
    status: VerificationStatus;
    applicationId?: ApplicationId;
    rejectionReason?: string;
    customerId: UserId;
    docType: DocumentType;
    uploadedAt: Timestamp;
    fileReference: string;
}
export interface DisbursementInput {
    referenceNumber: string;
    ifscCode: string;
    bankName: string;
    accountNumber: string;
}
export interface CustomerProfileInput {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export type ApplicationFilter = {
    __kind__: "all";
    all: null;
} | {
    __kind__: "byCustomer";
    byCustomer: UserId;
} | {
    __kind__: "byStatus";
    byStatus: ApplicationStatus;
};
export interface CibilRecord {
    requestId: string;
    isEligible: boolean;
    score: bigint;
    checkedAt: Timestamp;
    customerId: UserId;
    reportSummary: string;
}
export interface DocumentUploadInput {
    applicationId?: ApplicationId;
    docType: DocumentType;
    fileReference: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ApplicationSummary {
    id: ApplicationId;
    customerName: string;
    status: ApplicationStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    customerId: UserId;
    amountRequested: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: LoanApplication;
} | {
    __kind__: "err";
    err: string;
};
export type LoanPurpose = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "home";
    home: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "personal";
    personal: null;
} | {
    __kind__: "business";
    business: null;
} | {
    __kind__: "vehicle";
    vehicle: null;
} | {
    __kind__: "medical";
    medical: null;
};
export type Result_4 = {
    __kind__: "ok";
    ok: DocumentRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface KycRecord {
    status: VerificationStatus;
    identityType: IdentityType;
    rejectionReason?: string;
    submittedAt: Timestamp;
    reviewedAt?: Timestamp;
    identityNumber: string;
    customerId: UserId;
}
export interface AdminRejectInput {
    rejectionReason: string;
}
export interface LoanApplication {
    id: ApplicationId;
    status: ApplicationStatus;
    approvedAt?: Timestamp;
    createdAt: Timestamp;
    rejectionReason?: string;
    submittedAt?: Timestamp;
    processingFeePayment?: StripePayment;
    updatedAt: Timestamp;
    tenureMonths: bigint;
    interestRate?: number;
    cibilRecordId?: string;
    customerId: UserId;
    disbursement?: DisbursementRecord;
    adminNotes?: string;
    amountRequested: bigint;
    approvedAmount?: bigint;
    purpose: LoanPurpose;
}
export interface LoanApplicationInput {
    tenureMonths: bigint;
    amountRequested: bigint;
    purpose: LoanPurpose;
}
export interface KycSubmitInput {
    identityType: IdentityType;
    identityNumber: string;
}
export interface ApplicationDetails {
    kyc?: KycRecord;
    documents: Array<DocumentRecord>;
    application: LoanApplication;
    customer?: CustomerProfile;
    cibil?: CibilRecord;
}
export interface CustomerProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    address: string;
    phone: string;
}
export interface AdminApproveInput {
    interestRate: number;
    adminNotes?: string;
    approvedAmount: bigint;
}
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: CustomerProfile;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: CibilRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface DisbursementRecord {
    referenceNumber: string;
    ifscCode: string;
    applicationId: ApplicationId;
    bankName: string;
    accountNumber: string;
    amount: bigint;
    disbursedAt: Timestamp;
}
export type ApplicationId = string;
export interface StripePayment {
    status: PaymentStatus;
    createdAt: Timestamp;
    currency: string;
    amount: bigint;
    paidAt?: Timestamp;
    paymentIntentId: string;
}
export enum ApplicationStatus {
    submitted = "submitted",
    kycPending = "kycPending",
    underReview = "underReview",
    documentsPending = "documentsPending",
    disbursed = "disbursed",
    cibilPending = "cibilPending",
    approved = "approved",
    rejected = "rejected",
    draft = "draft",
    paymentPending = "paymentPending"
}
export enum IdentityType {
    pan = "pan",
    aadhaar = "aadhaar",
    drivingLicense = "drivingLicense"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum VerificationStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export interface backendInterface {
    addAdmin(newAdmin: UserId): Promise<Result_5>;
    addDocument(input: DocumentUploadInput): Promise<Result_4>;
    adminApproveApplication(appId: ApplicationId, input: AdminApproveInput): Promise<Result_1>;
    adminGetApplicationDetails(appId: ApplicationId): Promise<ApplicationDetails | null>;
    adminListApplications(filterBy: ApplicationFilter): Promise<Array<ApplicationSummary>>;
    adminRecordDisbursement(appId: ApplicationId, input: DisbursementInput): Promise<Result_1>;
    adminRejectApplication(appId: ApplicationId, input: AdminRejectInput): Promise<Result_1>;
    adminReviewDocument(docId: string, approved: boolean, reason: string | null): Promise<Result_4>;
    adminReviewKyc(customerId: UserId, approved: boolean, reason: string | null): Promise<Result_2>;
    createCustomerProfile(input: CustomerProfileInput): Promise<Result>;
    createLoanApplication(input: LoanApplicationInput): Promise<Result_1>;
    getMyApplication(appId: ApplicationId): Promise<LoanApplication | null>;
    getMyCibilRecord(): Promise<CibilRecord | null>;
    getMyDocuments(applicationId: ApplicationId | null): Promise<Array<DocumentRecord>>;
    getMyKycStatus(): Promise<KycRecord | null>;
    getMyProfile(): Promise<CustomerProfile | null>;
    listMyApplications(): Promise<Array<LoanApplication>>;
    recordCibilCheck(customerId: UserId, score: bigint, reportSummary: string, requestId: string): Promise<Result_3>;
    recordPayment(appId: ApplicationId, payment: StripePayment): Promise<Result_1>;
    submitKyc(input: KycSubmitInput): Promise<Result_2>;
    submitLoanApplication(appId: ApplicationId): Promise<Result_1>;
    updateCustomerProfile(input: CustomerProfileInput): Promise<Result>;
}
import type { AdminApproveInput as _AdminApproveInput, ApplicationDetails as _ApplicationDetails, ApplicationFilter as _ApplicationFilter, ApplicationId as _ApplicationId, ApplicationStatus as _ApplicationStatus, ApplicationSummary as _ApplicationSummary, CibilRecord as _CibilRecord, CustomerProfile as _CustomerProfile, DisbursementRecord as _DisbursementRecord, DocumentRecord as _DocumentRecord, DocumentType as _DocumentType, DocumentUploadInput as _DocumentUploadInput, IdentityType as _IdentityType, KycRecord as _KycRecord, KycSubmitInput as _KycSubmitInput, LoanApplication as _LoanApplication, LoanApplicationInput as _LoanApplicationInput, LoanPurpose as _LoanPurpose, PaymentStatus as _PaymentStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, StripePayment as _StripePayment, Timestamp as _Timestamp, UserId as _UserId, VerificationStatus as _VerificationStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: UserId): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return from_candid_Result_5_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDocument(arg0: DocumentUploadInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(to_candid_DocumentUploadInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_4_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(to_candid_DocumentUploadInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_4_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApproveApplication(arg0: ApplicationId, arg1: AdminApproveInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveApplication(arg0, to_candid_AdminApproveInput_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveApplication(arg0, to_candid_AdminApproveInput_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetApplicationDetails(arg0: ApplicationId): Promise<ApplicationDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetApplicationDetails(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetApplicationDetails(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListApplications(arg0: ApplicationFilter): Promise<Array<ApplicationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListApplications(to_candid_ApplicationFilter_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListApplications(to_candid_ApplicationFilter_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRecordDisbursement(arg0: ApplicationId, arg1: DisbursementInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRecordDisbursement(arg0, arg1);
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRecordDisbursement(arg0, arg1);
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectApplication(arg0: ApplicationId, arg1: AdminRejectInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectApplication(arg0, arg1);
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectApplication(arg0, arg1);
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminReviewDocument(arg0: string, arg1: boolean, arg2: string | null): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReviewDocument(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_4_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReviewDocument(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_4_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminReviewKyc(arg0: UserId, arg1: boolean, arg2: string | null): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReviewKyc(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReviewKyc(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomerProfile(arg0: CustomerProfileInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomerProfile(arg0);
                return from_candid_Result_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomerProfile(arg0);
            return from_candid_Result_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLoanApplication(arg0: LoanApplicationInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoanApplication(to_candid_LoanApplicationInput_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoanApplication(to_candid_LoanApplicationInput_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplication(arg0: ApplicationId): Promise<LoanApplication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplication(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplication(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCibilRecord(): Promise<CibilRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCibilRecord();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCibilRecord();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDocuments(arg0: ApplicationId | null): Promise<Array<DocumentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDocuments(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDocuments(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyKycStatus(): Promise<KycRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKycStatus();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKycStatus();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyApplications();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyApplications();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordCibilCheck(arg0: UserId, arg1: bigint, arg2: string, arg3: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCibilCheck(arg0, arg1, arg2, arg3);
                return from_candid_Result_3_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCibilCheck(arg0, arg1, arg2, arg3);
            return from_candid_Result_3_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayment(arg0: ApplicationId, arg1: StripePayment): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, to_candid_StripePayment_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, to_candid_StripePayment_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitKyc(arg0: KycSubmitInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKyc(to_candid_KycSubmitInput_n72(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKyc(to_candid_KycSubmitInput_n72(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLoanApplication(arg0: ApplicationId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLoanApplication(arg0);
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLoanApplication(arg0);
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomerProfile(arg0: CustomerProfileInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerProfile(arg0);
                return from_candid_Result_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerProfile(arg0);
            return from_candid_Result_n57(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApplicationDetails_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationDetails): ApplicationDetails {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationSummary_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationSummary): ApplicationSummary {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentRecord): DocumentRecord {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_IdentityType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdentityType): IdentityType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_KycRecord_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycRecord): KycRecord {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplication_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LoanPurpose_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanPurpose): LoanPurpose {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_StripePayment_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripePayment): StripePayment {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApplicationId]): ApplicationId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripePayment]): StripePayment | null {
    return value.length === 0 ? null : from_candid_StripePayment_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DisbursementRecord]): DisbursementRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApplicationDetails]): ApplicationDetails | null {
    return value.length === 0 ? null : from_candid_ApplicationDetails_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KycRecord]): KycRecord | null {
    return value.length === 0 ? null : from_candid_KycRecord_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CibilRecord]): CibilRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LoanApplication]): LoanApplication | null {
    return value.length === 0 ? null : from_candid_LoanApplication_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _VerificationStatus;
    applicationId: [] | [_ApplicationId];
    rejectionReason: [] | [string];
    customerId: _UserId;
    docType: _DocumentType;
    uploadedAt: _Timestamp;
    fileReference: string;
}): {
    id: string;
    status: VerificationStatus;
    applicationId?: ApplicationId;
    rejectionReason?: string;
    customerId: UserId;
    docType: DocumentType;
    uploadedAt: Timestamp;
    fileReference: string;
} {
    return {
        id: value.id,
        status: from_candid_VerificationStatus_n11(_uploadFile, _downloadFile, value.status),
        applicationId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.applicationId)),
        rejectionReason: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.rejectionReason)),
        customerId: value.customerId,
        docType: from_candid_DocumentType_n15(_uploadFile, _downloadFile, value.docType),
        uploadedAt: value.uploadedAt,
        fileReference: value.fileReference
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ApplicationId;
    status: _ApplicationStatus;
    approvedAt: [] | [_Timestamp];
    createdAt: _Timestamp;
    rejectionReason: [] | [string];
    submittedAt: [] | [_Timestamp];
    processingFeePayment: [] | [_StripePayment];
    updatedAt: _Timestamp;
    tenureMonths: bigint;
    interestRate: [] | [number];
    cibilRecordId: [] | [string];
    customerId: _UserId;
    disbursement: [] | [_DisbursementRecord];
    adminNotes: [] | [string];
    amountRequested: bigint;
    approvedAmount: [] | [bigint];
    purpose: _LoanPurpose;
}): {
    id: ApplicationId;
    status: ApplicationStatus;
    approvedAt?: Timestamp;
    createdAt: Timestamp;
    rejectionReason?: string;
    submittedAt?: Timestamp;
    processingFeePayment?: StripePayment;
    updatedAt: Timestamp;
    tenureMonths: bigint;
    interestRate?: number;
    cibilRecordId?: string;
    customerId: UserId;
    disbursement?: DisbursementRecord;
    adminNotes?: string;
    amountRequested: bigint;
    approvedAmount?: bigint;
    purpose: LoanPurpose;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n23(_uploadFile, _downloadFile, value.status),
        approvedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.approvedAt)),
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.submittedAt)),
        processingFeePayment: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.processingFeePayment)),
        updatedAt: value.updatedAt,
        tenureMonths: value.tenureMonths,
        interestRate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.interestRate)),
        cibilRecordId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cibilRecordId)),
        customerId: value.customerId,
        disbursement: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.disbursement)),
        adminNotes: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.adminNotes)),
        amountRequested: value.amountRequested,
        approvedAmount: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.approvedAmount)),
        purpose: from_candid_LoanPurpose_n34(_uploadFile, _downloadFile, value.purpose)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    createdAt: _Timestamp;
    currency: string;
    amount: bigint;
    paidAt: [] | [_Timestamp];
    paymentIntentId: string;
}): {
    status: PaymentStatus;
    createdAt: Timestamp;
    currency: string;
    amount: bigint;
    paidAt?: Timestamp;
    paymentIntentId: string;
} {
    return {
        status: from_candid_PaymentStatus_n29(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        currency: value.currency,
        amount: value.amount,
        paidAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.paidAt)),
        paymentIntentId: value.paymentIntentId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kyc: [] | [_KycRecord];
    documents: Array<_DocumentRecord>;
    application: _LoanApplication;
    customer: [] | [_CustomerProfile];
    cibil: [] | [_CibilRecord];
}): {
    kyc?: KycRecord;
    documents: Array<DocumentRecord>;
    application: LoanApplication;
    customer?: CustomerProfile;
    cibil?: CibilRecord;
} {
    return {
        kyc: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.kyc)),
        documents: from_candid_vec_n44(_uploadFile, _downloadFile, value.documents),
        application: from_candid_LoanApplication_n21(_uploadFile, _downloadFile, value.application),
        customer: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.customer)),
        cibil: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.cibil))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VerificationStatus;
    identityType: _IdentityType;
    rejectionReason: [] | [string];
    submittedAt: _Timestamp;
    reviewedAt: [] | [_Timestamp];
    identityNumber: string;
    customerId: _UserId;
}): {
    status: VerificationStatus;
    identityType: IdentityType;
    rejectionReason?: string;
    submittedAt: Timestamp;
    reviewedAt?: Timestamp;
    identityNumber: string;
    customerId: UserId;
} {
    return {
        status: from_candid_VerificationStatus_n11(_uploadFile, _downloadFile, value.status),
        identityType: from_candid_IdentityType_n42(_uploadFile, _downloadFile, value.identityType),
        rejectionReason: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.reviewedAt)),
        identityNumber: value.identityNumber,
        customerId: value.customerId
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ApplicationId;
    customerName: string;
    status: _ApplicationStatus;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    customerId: _UserId;
    amountRequested: bigint;
}): {
    id: ApplicationId;
    customerName: string;
    status: ApplicationStatus;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    customerId: UserId;
    amountRequested: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_ApplicationStatus_n23(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        customerId: value.customerId,
        amountRequested: value.amountRequested
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "pending" in value ? VerificationStatus.pending : "rejected" in value ? VerificationStatus.rejected : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    bankStatement: null;
} | {
    incomeProof: null;
} | {
    identityProof: null;
} | {
    photograph: null;
} | {
    addressProof: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bankStatement";
    bankStatement: null;
} | {
    __kind__: "incomeProof";
    incomeProof: null;
} | {
    __kind__: "identityProof";
    identityProof: null;
} | {
    __kind__: "photograph";
    photograph: null;
} | {
    __kind__: "addressProof";
    addressProof: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "bankStatement" in value ? {
        __kind__: "bankStatement",
        bankStatement: value.bankStatement
    } : "incomeProof" in value ? {
        __kind__: "incomeProof",
        incomeProof: value.incomeProof
    } : "identityProof" in value ? {
        __kind__: "identityProof",
        identityProof: value.identityProof
    } : "photograph" in value ? {
        __kind__: "photograph",
        photograph: value.photograph
    } : "addressProof" in value ? {
        __kind__: "addressProof",
        addressProof: value.addressProof
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LoanApplication;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LoanApplication;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LoanApplication_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    kycPending: null;
} | {
    underReview: null;
} | {
    documentsPending: null;
} | {
    disbursed: null;
} | {
    cibilPending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} | {
    paymentPending: null;
}): ApplicationStatus {
    return "submitted" in value ? ApplicationStatus.submitted : "kycPending" in value ? ApplicationStatus.kycPending : "underReview" in value ? ApplicationStatus.underReview : "documentsPending" in value ? ApplicationStatus.documentsPending : "disbursed" in value ? ApplicationStatus.disbursed : "cibilPending" in value ? ApplicationStatus.cibilPending : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : "draft" in value ? ApplicationStatus.draft : "paymentPending" in value ? ApplicationStatus.paymentPending : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    home: null;
} | {
    education: null;
} | {
    personal: null;
} | {
    business: null;
} | {
    vehicle: null;
} | {
    medical: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "home";
    home: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "personal";
    personal: null;
} | {
    __kind__: "business";
    business: null;
} | {
    __kind__: "vehicle";
    vehicle: null;
} | {
    __kind__: "medical";
    medical: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "home" in value ? {
        __kind__: "home",
        home: value.home
    } : "education" in value ? {
        __kind__: "education",
        education: value.education
    } : "personal" in value ? {
        __kind__: "personal",
        personal: value.personal
    } : "business" in value ? {
        __kind__: "business",
        business: value.business
    } : "vehicle" in value ? {
        __kind__: "vehicle",
        vehicle: value.vehicle
    } : "medical" in value ? {
        __kind__: "medical",
        medical: value.medical
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
}): IdentityType {
    return "pan" in value ? IdentityType.pan : "aadhaar" in value ? IdentityType.aadhaar : "drivingLicense" in value ? IdentityType.drivingLicense : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _KycRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: KycRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_KycRecord_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CustomerProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CibilRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CibilRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DocumentRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DocumentRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DocumentRecord_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentRecord>): Array<DocumentRecord> {
    return value.map((x)=>from_candid_DocumentRecord_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationSummary>): Array<ApplicationSummary> {
    return value.map((x)=>from_candid_ApplicationSummary_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplication>): Array<LoanApplication> {
    return value.map((x)=>from_candid_LoanApplication_n21(_uploadFile, _downloadFile, x));
}
function to_candid_AdminApproveInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminApproveInput): _AdminApproveInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationFilter_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationFilter): _ApplicationFilter {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentUploadInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentUploadInput): _DocumentUploadInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_IdentityType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdentityType): _IdentityType {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_KycSubmitInput_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycSubmitInput): _KycSubmitInput {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_LoanApplicationInput_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanApplicationInput): _LoanApplicationInput {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_LoanPurpose_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanPurpose): _LoanPurpose {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_StripePayment_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripePayment): _StripePayment {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationId | null): [] | [_ApplicationId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interestRate: number;
    adminNotes?: string;
    approvedAmount: bigint;
}): {
    interestRate: number;
    adminNotes: [] | [string];
    approvedAmount: bigint;
} {
    return {
        interestRate: value.interestRate,
        adminNotes: value.adminNotes ? candid_some(value.adminNotes) : candid_none(),
        approvedAmount: value.approvedAmount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicationId?: ApplicationId;
    docType: DocumentType;
    fileReference: string;
}): {
    applicationId: [] | [_ApplicationId];
    docType: _DocumentType;
    fileReference: string;
} {
    return {
        applicationId: value.applicationId ? candid_some(value.applicationId) : candid_none(),
        docType: to_candid_DocumentType_n5(_uploadFile, _downloadFile, value.docType),
        fileReference: value.fileReference
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tenureMonths: bigint;
    amountRequested: bigint;
    purpose: LoanPurpose;
}): {
    tenureMonths: bigint;
    amountRequested: bigint;
    purpose: _LoanPurpose;
} {
    return {
        tenureMonths: value.tenureMonths,
        amountRequested: value.amountRequested,
        purpose: to_candid_LoanPurpose_n61(_uploadFile, _downloadFile, value.purpose)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PaymentStatus;
    createdAt: Timestamp;
    currency: string;
    amount: bigint;
    paidAt?: Timestamp;
    paymentIntentId: string;
}): {
    status: _PaymentStatus;
    createdAt: _Timestamp;
    currency: string;
    amount: bigint;
    paidAt: [] | [_Timestamp];
    paymentIntentId: string;
} {
    return {
        status: to_candid_PaymentStatus_n70(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        currency: value.currency,
        amount: value.amount,
        paidAt: value.paidAt ? candid_some(value.paidAt) : candid_none(),
        paymentIntentId: value.paymentIntentId
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    identityType: IdentityType;
    identityNumber: string;
}): {
    identityType: _IdentityType;
    identityNumber: string;
} {
    return {
        identityType: to_candid_IdentityType_n74(_uploadFile, _downloadFile, value.identityType),
        identityNumber: value.identityNumber
    };
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "all";
    all: null;
} | {
    __kind__: "byCustomer";
    byCustomer: UserId;
} | {
    __kind__: "byStatus";
    byStatus: ApplicationStatus;
}): {
    all: null;
} | {
    byCustomer: _UserId;
} | {
    byStatus: _ApplicationStatus;
} {
    return value.__kind__ === "all" ? {
        all: value.all
    } : value.__kind__ === "byCustomer" ? {
        byCustomer: value.byCustomer
    } : value.__kind__ === "byStatus" ? {
        byStatus: to_candid_ApplicationStatus_n49(_uploadFile, _downloadFile, value.byStatus)
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    submitted: null;
} | {
    kycPending: null;
} | {
    underReview: null;
} | {
    documentsPending: null;
} | {
    disbursed: null;
} | {
    cibilPending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} | {
    paymentPending: null;
} {
    return value == ApplicationStatus.submitted ? {
        submitted: null
    } : value == ApplicationStatus.kycPending ? {
        kycPending: null
    } : value == ApplicationStatus.underReview ? {
        underReview: null
    } : value == ApplicationStatus.documentsPending ? {
        documentsPending: null
    } : value == ApplicationStatus.disbursed ? {
        disbursed: null
    } : value == ApplicationStatus.cibilPending ? {
        cibilPending: null
    } : value == ApplicationStatus.approved ? {
        approved: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.draft ? {
        draft: null
    } : value == ApplicationStatus.paymentPending ? {
        paymentPending: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bankStatement";
    bankStatement: null;
} | {
    __kind__: "incomeProof";
    incomeProof: null;
} | {
    __kind__: "identityProof";
    identityProof: null;
} | {
    __kind__: "photograph";
    photograph: null;
} | {
    __kind__: "addressProof";
    addressProof: null;
}): {
    other: string;
} | {
    bankStatement: null;
} | {
    incomeProof: null;
} | {
    identityProof: null;
} | {
    photograph: null;
} | {
    addressProof: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "bankStatement" ? {
        bankStatement: value.bankStatement
    } : value.__kind__ === "incomeProof" ? {
        incomeProof: value.incomeProof
    } : value.__kind__ === "identityProof" ? {
        identityProof: value.identityProof
    } : value.__kind__ === "photograph" ? {
        photograph: value.photograph
    } : value.__kind__ === "addressProof" ? {
        addressProof: value.addressProof
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "home";
    home: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "personal";
    personal: null;
} | {
    __kind__: "business";
    business: null;
} | {
    __kind__: "vehicle";
    vehicle: null;
} | {
    __kind__: "medical";
    medical: null;
}): {
    other: string;
} | {
    home: null;
} | {
    education: null;
} | {
    personal: null;
} | {
    business: null;
} | {
    vehicle: null;
} | {
    medical: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "home" ? {
        home: value.home
    } : value.__kind__ === "education" ? {
        education: value.education
    } : value.__kind__ === "personal" ? {
        personal: value.personal
    } : value.__kind__ === "business" ? {
        business: value.business
    } : value.__kind__ === "vehicle" ? {
        vehicle: value.vehicle
    } : value.__kind__ === "medical" ? {
        medical: value.medical
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdentityType): {
    pan: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
} {
    return value == IdentityType.pan ? {
        pan: null
    } : value == IdentityType.aadhaar ? {
        aadhaar: null
    } : value == IdentityType.drivingLicense ? {
        drivingLicense: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
